// Opens a generated repository in the canvas.
//
// Stands in for the Tauri scan until that lands, and stays afterwards as the
// stress harness: the synthetic generator can produce repositories far larger
// than any real one, which is how the renderer's limits get found.

import type { CanvasApp } from '$lib/canvas/app';
import { synthRepo, type SynthRepo } from '$lib/canvas/data/synth';
import { decodeFile } from '$lib/canvas/data/wire';
import { PseudoText } from '$lib/canvas/data/pseudotext';
import { project, type FileGroup } from '$lib/state/project.svelte';

const params = new URLSearchParams(location.search);

/**
 * Whether the query asks for a generated repository of a particular shape.
 *
 * The layout check drives its cases through these, `?files=800&lines=12` and
 * so on, so they have to win over anything the page would otherwise open. The
 * web demo took that away for a while: every case loaded pathsim instead and
 * the check reported the same numbers eight times, which is the sort of
 * failure that looks like a layout regression.
 */
export function syntheticQuery(): boolean {
  return ['files', 'lines', 'stubs', 'dirs', 'depth', 'seed'].some((k) => params.has(k));
}
const num = (k: string, d: number) => {
  const v = params.get(k);
  return v === null ? d : Number(v);
};

/** Extensions the generator emits that stand in for generated artefacts, with
 *  the reason the real filter would give. */
const SYNTHETIC_ARTEFACTS: Record<string, string> = {
  json: 'large data file',
  md: 'generated by name',
};

let cached: SynthRepo | null = null;

function groupsOf(repo: SynthRepo): Omit<FileGroup, 'mode'>[] {
  const acc = new Map<string, { files: number; lines: number }>();
  for (const e of repo.entries) {
    const dot = e.path.lastIndexOf('.');
    const slash = e.path.lastIndexOf('/');
    const ext = dot > slash ? e.path.slice(dot + 1) : '(none)';
    const g = acc.get(ext) ?? { files: 0, lines: 0 };
    g.files++;
    g.lines += e.lineCount;
    acc.set(ext, g);
  }
  return [...acc].map(([id, g]) => ({
    id,
    files: g.files,
    lines: g.lines,
    artefact: SYNTHETIC_ARTEFACTS[id],
  }));
}

/**
 * Build the scene from the generated repo and whatever the view picker says.
 *
 * `regenerate` draws a new repository; otherwise the same one is re-laid out,
 * which is what a change in the picker needs.
 */
export function openSynthetic(app: CanvasApp, regenerate = false, keepView = false): void {
  if (!cached || regenerate) {
    cached = synthRepo({
      fileCount: num('files', 400),
      seed: regenerate && cached ? Math.floor(Math.random() * 1e6) : num('seed', 7),
      medianLines: num('lines', 180),
      changedFraction: num('changed', 0.03),
    });
    project.load('generated', groupsOf(cached), true);
  }
  const repo = cached;

  // `?stubs=<fraction>` reduces that share of the files to placeholders
  // without going through the picker, so a check can exercise the mode. Taken
  // by a hash of the path rather than at random, so the same query gives the
  // same layout twice.
  const stubbed = num('stubs', 0);
  const reduced = (path: string): boolean => {
    if (project.modeForPath(path) === 'reduced') return true;
    if (stubbed <= 0) return false;
    let h = 2166136261;
    for (let i = 0; i < path.length; i++) h = ((h ^ path.charCodeAt(i)) * 16777619) >>> 0;
    return (h % 1000) / 1000 < stubbed;
  };

  // `?media=<fraction>` turns that share of the files into pictures, so the
  // layout check can hold its invariants over a project that has some. Sizes
  // come from the path hash as well: a plot, a diagram, an icon, which is the
  // spread a real repository has.
  const pictures = num('media', 0);
  const asPicture = (path: string) => {
    if (pictures <= 0) return undefined;
    let h = 2166136261;
    for (let i = 0; i < path.length; i++) h = ((h ^ path.charCodeAt(i)) * 16777619) >>> 0;
    if ((h % 1000) / 1000 >= pictures) return undefined;
    const shapes = [
      { w: 3900, h: 700 },
      { w: 1600, h: 900 },
      { w: 1024, h: 1024 },
      { w: 256, h: 256 },
      { w: 32, h: 32 },
    ];
    const pick = shapes[h % shapes.length];
    return { kind: 'image' as const, w: pick.w, h: pick.h, pages: 0 };
  };

  const entries = repo.entries
    .map((e) => {
      const media = asPicture(e.path);
      // A picture has no lines, so it arrives the way the backend sends one.
      return media
        ? { ...e, media, lineCount: 0, maxCols: 0, clipCols: 0, lineCols: undefined, stub: false }
        : { ...e, stub: reduced(e.path) };
    })
    .filter((e) => project.modeForPath(e.path) !== 'off');

  app.open(
    {
      entries,
      payload: (path) => repo.payloads.get(path),
      text: new PseudoText(
        new Map([...repo.payloads].map(([p, buf]) => [p, decodeFile(buf)])),
      ),
    },
    keepView,
  );
}
