// Opens a generated repository in the canvas.
//
// Stands in for the Tauri scan until that lands, and stays afterwards as the
// stress harness: the synthetic generator can produce repositories far larger
// than any real one, which is how the renderer's limits get found.

import type { CanvasApp } from '$lib/canvas/app';
import { synthRepo, type SynthRepo } from '$lib/canvas/data/synth';
import { decodeFile } from '$lib/canvas/data/wire';
import { PseudoText } from '$lib/canvas/data/pseudotext';
import { project, type FileGroup } from '$lib/state/project.svelte';

const params = new URLSearchParams(location.search);
const num = (k: string, d: number) => {
  const v = params.get(k);
  return v === null ? d : Number(v);
};

/** Extensions the generator emits that stand in for generated artefacts, with
 *  the reason the real filter would give. */
const SYNTHETIC_ARTEFACTS: Record<string, string> = {
  json: 'large data file',
  md: 'generated by name',
};

let cached: SynthRepo | null = null;

function groupsOf(repo: SynthRepo): Omit<FileGroup, 'mode'>[] {
  const acc = new Map<string, { files: number; lines: number }>();
  for (const e of repo.entries) {
    const dot = e.path.lastIndexOf('.');
    const slash = e.path.lastIndexOf('/');
    const ext = dot > slash ? e.path.slice(dot + 1) : '(none)';
    const g = acc.get(ext) ?? { files: 0, lines: 0 };
    g.files++;
    g.lines += e.lineCount;
    acc.set(ext, g);
  }
  return [...acc].map(([id, g]) => ({
    id,
    files: g.files,
    lines: g.lines,
    artefact: SYNTHETIC_ARTEFACTS[id],
  }));
}

/**
 * Build the scene from the generated repo and whatever the view picker says.
 *
 * `regenerate` draws a new repository; otherwise the same one is re-laid out,
 * which is what a change in the picker needs.
 */
export function openSynthetic(app: CanvasApp, regenerate = false, keepView = false): void {
  if (!cached || regenerate) {
    cached = synthRepo({
      fileCount: num('files', 400),
      seed: regenerate && cached ? Math.floor(Math.random() * 1e6) : num('seed', 7),
      medianLines: num('lines', 180),
      changedFraction: num('changed', 0.03),
    });
    project.load('generated', groupsOf(cached), true);
  }
  const repo = cached;

  const entries = repo.entries
    .map((e) => ({ ...e, stub: project.modeForPath(e.path) === 'reduced' }))
    .filter((e) => project.modeForPath(e.path) !== 'off');

  app.open(
    {
      entries,
      payload: (path) => repo.payloads.get(path),
      text: new PseudoText(
        new Map([...repo.payloads].map(([p, buf]) => [p, decodeFile(buf)])),
      ),
    },
    keepView,
  );
}
