// Generates the logo in all its forms from one drawing, web/scripts/logo.mjs:
//
//   web/src/lib/ui/SanityMark.svelte   the wordmark in the toolbar, in the
//                                      theme's accent
//   assets/sanity-logo.svg             the wordmark in the logo's red, for the
//                                      README and anywhere else
//   assets/sanity-icon.svg             the app icon
//   web/public/favicon.svg             the browser tab
//
// The icons are the mark: the S and the y and the frame the two rails make,
// with the letters between left out. What made the logo recognisable is that
// frame, the top rail running out of the S and the bottom one into the tail
// of the y, and a square with both ends of it keeps the frame closed.
//
// Generated rather than hand-written because the variants differ in
// proportion and have to stay the same drawing otherwise:
//
//   The app icon follows Apple's grid, a body of 824 in a 1024 canvas with a
//   185 radius. Filling the canvas instead makes it sit visibly larger than
//   its neighbours in the Dock.
//
//   The favicon is full bleed with a smaller radius and a larger mark: it is
//   read at sixteen pixels, where every pixel of margin is one the letters
//   do not get.
//
// Run through `npm run icons`, which also renders the PNGs.

import { writeFileSync } from 'node:fs';
import { wordmark, wordmarkBody } from './logo.mjs';

/** The weight everything is drawn at, in the original's pixels, where the
 *  original's own is 48: a fifth heavier, which holds up at the toolbar's
 *  fifteen pixels, where 48 came out a pixel and a half. */
const STROKE = 58;

const CHARCOAL = '#16181a';
/** The logo's own red. */
const RED = '#ff0000';

const r = (v) => Math.round(v * 1000) / 1000;

/** The mark in a body of `body` at `radius`, taking `share` of the body's side. */
function icon({ body, radius, share }) {
  const m = wordmark(STROKE, { letters: false });
  const k = (body.w * share) / Math.max(m.width, m.height);
  const x = body.x + (body.w - m.width * k) / 2;
  const y = body.y + (body.h - m.height * k) / 2;
  return [
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">',
    '<title>sanity</title>',
    `<rect x="${body.x}" y="${body.y}" width="${body.w}" height="${body.h}" rx="${radius}" fill="${CHARCOAL}"/>`,
    wordmarkBody(m, RED, 'sanity-cut', `translate(${r(x)} ${r(y)}) scale(${r(k)})`),
    '</svg>',
    '',
  ].join('\n');
}

// Apple's grid: a body of 824 centred in 1024, radius 185.
writeFileSync('assets/sanity-icon.svg', icon({ body: { x: 100, y: 100, w: 824, h: 824 }, radius: 185, share: 0.62 }));
writeFileSync('web/public/favicon.svg', icon({ body: { x: 0, y: 0, w: 1024, h: 1024 }, radius: 150, share: 0.8 }));

const w = wordmark(STROKE);
writeFileSync(
  'assets/sanity-logo.svg',
  [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w.width} ${w.height}" width="${w.width}" height="${w.height}">`,
    '<title>sanity</title>',
    wordmarkBody(w, RED),
    '</svg>',
    '',
  ].join('\n'),
);

// The toolbar's, in `currentColor`, which its style sets to the theme's
// accent: the red in the sanity theme, and in the others the colour the rest
// of their interface is picked out in.
writeFileSync(
  'web/src/lib/ui/SanityMark.svelte',
  `<script lang="ts">
	// Generated by web/scripts/make-icon.mjs from the drawing in
	// web/scripts/logo.mjs. Edit those, not this.
	let { height = 16 }: { height?: number } = $props();
</script>

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w.width} ${w.height}" height={height} width={(height * ${w.width}) / ${w.height}} role="img" aria-label="sanity">
${wordmarkBody(w, 'currentColor', 'sanity-mark-cut')}
</svg>

<style>
	svg {
		display: block;
		flex: none;
		color: var(--accent);
	}
</style>
`,
);

console.log(`logo, icon, favicon and SanityMark written, at a stroke of ${STROKE}`);
