// Generates the mark in its three forms: assets/sanity-icon.svg for the app
// icon, web/public/favicon.svg for the browser tab, and the Svelte component
// the toolbar draws, which is the wordmark whole.
//
// The mark is the wordmark, assets/sanity-logo.png, brought to a square: its
// S and its y, and the two rails that frame the word, with the letters in
// between left out. It is cut from the original's own pixels and traced, not
// redrawn, so it is the logo's shapes and nothing else. What made the logo
// recognisable is that frame, the top rail running out of the S and the
// bottom one into the tail of the y, and a square with both ends of it keeps
// the frame closed.
//
// This replaced a drawing of what the app draws, panels sized by their code
// with one of them red, which had nothing of the logo in it.
//
// Generated rather than hand-written because the variants differ in
// proportion and have to stay the same drawing otherwise:
//
//   The app icon follows Apple's grid, a body of 824 in a 1024 canvas with a
//   185 radius. Filling the canvas instead makes it sit visibly larger than
//   its neighbours in the Dock.
//
//   The favicon is full bleed with a smaller radius and a larger mark: it is
//   read at sixteen pixels, where every pixel of margin is one the letters
//   do not get.

import { writeFileSync } from 'node:fs';
import { readMask, trace } from './trace-logo.mjs';

const CHARCOAL = '#16181a';
/** The logo's own red. */
const RED = '#ff0000';

/** Width of the square the S and the y are brought into, in the original's
 *  pixels: the two letters, 205 and 199 wide, and a gap between them about
 *  as wide as the logo's own between letters. */
const SPAN = 480;
/** Where the S ends and the y begins in the original, and the rows the rails
 *  take up. */
const S_END = 205;
const Y_START = 915;
const TOP_RAIL = 50;
const BOTTOM_RAIL = 414;

const logo = readMask('assets/sanity-logo.png');
const half = SPAN / 2;
const rail = (y) => y < TOP_RAIL || y >= BOTTOM_RAIL;
// Left half from the start of the word, right half from its end: the letters
// whole, and between them only the rails.
const on = (x, y) => {
  if (x < half) return (x < S_END || rail(y)) && logo.on(x, y);
  const lx = x + (logo.w - SPAN);
  return (lx >= Y_START || rail(y)) && logo.on(lx, y);
};
const d = trace(on, SPAN, logo.h);

const r = (v) => Math.round(v * 100) / 100;

/** The mark in a body of `body` at `radius`, taking `share` of the body's side. */
function build({ body, radius, share, fill = CHARCOAL, ink = RED }) {
  const k = (body.w * share) / Math.max(SPAN, logo.h);
  const x = body.x + (body.w - SPAN * k) / 2;
  const y = body.y + (body.h - logo.h * k) / 2;
  return [
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">',
    '  <title>sanity</title>',
    `  <rect x="${body.x}" y="${body.y}" width="${body.w}" height="${body.h}" rx="${radius}" fill="${fill}"/>`,
    `  <path transform="translate(${r(x)} ${r(y)}) scale(${r(k * 1000) / 1000})" fill="${ink}" d="${d}"/>`,
    '</svg>',
    '',
  ].join('\n');
}

// Apple's grid: a body of 824 centred in 1024, radius 185.
writeFileSync('assets/sanity-icon.svg', build({ body: { x: 100, y: 100, w: 824, h: 824 }, radius: 185, share: 0.62 }));
writeFileSync('web/public/favicon.svg', build({ body: { x: 0, y: 0, w: 1024, h: 1024 }, radius: 150, share: 0.8 }));

// The toolbar has room across, so it shows the wordmark itself, whole and
// traced, in the logo's red: the square is only for the places that ask for
// one. The red does not follow the theme: it is the signature.
const word = trace(logo.on, logo.w, logo.h);
const wordmark = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${logo.w} ${logo.h}" height={height} width={(height * ${logo.w}) / ${logo.h}} role="img" aria-label="sanity">
  <path fill="var(--sanity-red)" d="${word}"/>
</svg>
`;

writeFileSync(
  'web/src/lib/ui/SanityMark.svelte',
  `<script lang="ts">
	// Generated by web/scripts/make-icon.mjs. Edit that, not this: it is the
	// wordmark traced from assets/sanity-logo.png, and the app icon and the
	// favicon are cut from the same outline.
	let { height = 16 }: { height?: number } = $props();
</script>

${wordmark}
<style>
	svg {
		display: block;
		flex: none;
	}
</style>
`,
);

console.log(`icon, favicon and SanityMark written: the mark in ${d.length} characters of path, the wordmark in ${word.length}`);
