//! Which files belong in a structural overview.
//!
//! `git ls-files --cached --others --exclude-standard` answers the gitignore
//! question exactly, which takes care of `target/`, `node_modules/` and
//! `dist/`. It does not take care of generated files that are committed, and
//! measurement says that is the larger problem: the biggest repository in the
//! collection this was built against is 1.03 million lines of generated
//! `api.json` and 194 thousand lines of notebook output around 18 thousand
//! lines of actual source. Showing all of it is not a filter being strict, it
//! is a filter answering the wrong question.
//!
//! Three sources of truth, in descending authority:
//!
//! 1. `linguist-generated` in `.gitattributes`, the existing convention for
//!    exactly this, which the project owner has already curated.
//! 2. A default heuristic for what nobody marked up.
//! 3. Explicit rules, which are how a user overrides either of the above.

use std::collections::HashSet;
use std::path::Path;
use std::process::Command;

/// Suffixes that are generated often enough to exclude without asking. Not
/// extensions: `.pb.go` and `.min.js` need the compound.
const GENERATED_SUFFIXES: &[&str] = &[
    ".lock", ".snap", ".min.js", ".min.css", ".map", ".pb.go", ".pb.cc", ".pb.h",
    "_pb2.py", "_pb2_grpc.py", ".generated.ts", ".g.dart", ".freezed.dart",
];

/// File names that are generated wholesale.
const GENERATED_NAMES: &[&str] = &[
    "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "Cargo.lock", "poetry.lock",
    "composer.lock", "Gemfile.lock", "uv.lock", "go.sum",
];

/// Notebooks carry their outputs inline, which is what makes them enormous.
/// Excluded by default and worth revisiting: the code cells alone would be
/// worth showing, and extracting them is a tokeniser problem, not a filter
/// problem.
const NOTEBOOK_EXT: &str = ".ipynb";

/// Data-ish formats are only excluded above this many lines. A 40 line
/// `tsconfig.json` is part of how a project is put together; a 28 thousand
/// line `api.json` is a build product that happens to be committed.
const DATA_LINE_LIMIT: u32 = 2000;
const DATA_EXTENSIONS: &[&str] = &[".json", ".csv", ".tsv", ".xml", ".sql", ".ndjson", ".jsonl"];

/// Vector graphics get a much lower threshold than other data formats.
/// Hand-written icons are tens of lines; a plot exported from matplotlib or
/// a diagram tool is thousands. Measured on a docs repo that turned out to
/// carry 1.19 million lines of generated SVG in 587 files, which sailed
/// through the binary sniff because SVG is XML.
const VECTOR_LINE_LIMIT: u32 = 300;
const VECTOR_EXTENSIONS: &[&str] = &[".svg", ".dot", ".drawio"];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    Keep,
    /// Excluded, with the reason, so the UI can explain itself and offer a
    /// toggle rather than silently hiding a third of the repository.
    Artefact(Reason),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    LinguistGenerated,
    GeneratedName,
    Notebook,
    LargeDataFile,
    UserExcluded,
}

impl Reason {
    pub fn as_str(self) -> &'static str {
        match self {
            Reason::LinguistGenerated => "marked linguist-generated",
            Reason::GeneratedName => "generated by name",
            Reason::Notebook => "notebook with embedded output",
            Reason::LargeDataFile => "large data file",
            Reason::UserExcluded => "excluded by config",
        }
    }
}

#[derive(Debug, Default, Clone)]
pub struct Filter {
    /// Paths git reports as `linguist-generated`, relative with forward
    /// slashes. Populated by `load_gitattributes`.
    generated: HashSet<String>,
    /// Explicit user rules, matched as path suffixes so both a file and a
    /// directory prefix work.
    excluded: Vec<String>,
    included: Vec<String>,
    /// When set, nothing is treated as an artefact. This is the UI toggle:
    /// sometimes the question is how much generated weight a repo carries.
    pub show_artefacts: bool,
}

impl Filter {
    pub fn new() -> Self {
        Self::default()
    }

    /// Ask git which paths are marked `linguist-generated`. One call for the
    /// whole repository rather than one per file.
    pub fn load_gitattributes(&mut self, root: &Path, paths: &[String]) {
        let Some(stdout) =
            git_over_stdin(root, &["check-attr", "--stdin", "-z", "linguist-generated"], paths)
        else {
            return;
        };
        // Output is NUL separated triples: path, attribute, value.
        let fields: Vec<&[u8]> = stdout.split(|&b| b == 0).collect();
        for chunk in fields.chunks(3) {
            if chunk.len() < 3 {
                continue;
            }
            if chunk[2] == b"set" || chunk[2] == b"true" {
                self.generated.insert(String::from_utf8_lossy(chunk[0]).into_owned());
            }
        }
    }

    pub fn exclude(&mut self, pattern: impl Into<String>) {
        self.excluded.push(pattern.into());
    }

    /// Force a path back in, overriding every heuristic. This is how a project
    /// says that its committed JSON really is source.
    pub fn include(&mut self, pattern: impl Into<String>) {
        self.included.push(pattern.into());
    }

    fn matches(patterns: &[String], path: &str) -> bool {
        patterns.iter().any(|p| path == p.as_str() || path.starts_with(&format!("{p}/")))
    }

    /// Verdict without knowing the line count, which is all that can be
    /// decided before reading the file.
    pub fn classify(&self, path: &str) -> Verdict {
        if Self::matches(&self.included, path) {
            return Verdict::Keep;
        }
        if Self::matches(&self.excluded, path) {
            return Verdict::Artefact(Reason::UserExcluded);
        }
        if self.generated.contains(path) {
            return Verdict::Artefact(Reason::LinguistGenerated);
        }
        let name = path.rsplit('/').next().unwrap_or(path);
        if GENERATED_NAMES.contains(&name) {
            return Verdict::Artefact(Reason::GeneratedName);
        }
        if GENERATED_SUFFIXES.iter().any(|s| path.ends_with(s)) {
            return Verdict::Artefact(Reason::GeneratedName);
        }
        if path.ends_with(NOTEBOOK_EXT) {
            return Verdict::Artefact(Reason::Notebook);
        }
        Verdict::Keep
    }

    /// Verdict once the line count is known. Separate from `classify` because
    /// the size rule cannot be applied before reading the file, and reading
    /// every file to find out is exactly what should be avoided.
    pub fn classify_sized(&self, path: &str, line_count: u32) -> Verdict {
        match self.classify(path) {
            Verdict::Artefact(r) => Verdict::Artefact(r),
            Verdict::Keep => {
                if Self::matches(&self.included, path) {
                    return Verdict::Keep;
                }
                let over = |exts: &[&str], limit: u32| {
                    exts.iter().any(|e| path.ends_with(e)) && line_count > limit
                };
                if over(DATA_EXTENSIONS, DATA_LINE_LIMIT)
                    || over(VECTOR_EXTENSIONS, VECTOR_LINE_LIMIT)
                {
                    Verdict::Artefact(Reason::LargeDataFile)
                } else {
                    Verdict::Keep
                }
            }
        }
    }

    /// The cheap pre-read decision used by `list_files`.
    pub fn keep(&self, _root: &Path, path: &str) -> bool {
        self.show_artefacts || self.classify(path) == Verdict::Keep
    }
}

/// Feed a NUL separated path list to a git subcommand on stdin and return its
/// stdout.
///
/// The write has to happen on its own thread. git answers as it reads, so on a
/// repository of any size its stdout pipe fills up long before the last path
/// has been written, and writing and reading from the same thread deadlocks
/// both processes. That is exactly what it did on a 1508 file repo.
///
/// The exit status is deliberately not checked: `check-ignore` exits 1 when
/// nothing matched, which is a perfectly good answer.
fn git_over_stdin(root: &Path, args: &[&str], paths: &[String]) -> Option<Vec<u8>> {
    if paths.is_empty() {
        return None;
    }
    let mut child = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(args)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null())
        .spawn()
        .ok()?;

    let stdin = child.stdin.take();
    let mut buf = Vec::with_capacity(paths.iter().map(|p| p.len() + 1).sum());
    for p in paths {
        buf.extend_from_slice(p.as_bytes());
        buf.push(0);
    }
    let writer = std::thread::spawn(move || {
        if let Some(mut s) = stdin {
            use std::io::Write;
            // A broken pipe here just means git stopped early; the paths that
            // did get through are still answered.
            let _ = s.write_all(&buf);
            let _ = s.flush();
        }
        // Dropping the handle closes the pipe, which is what tells git to stop
        // waiting for more input.
    });

    let out = child.wait_with_output().ok();
    let _ = writer.join();
    out.map(|o| o.stdout)
}

/// Which of `paths` git considers ignored.
///
/// Used by the watcher for paths the scan never saw: a build writing into
/// `target/` produces thousands of events, and the only correct answer to
/// whether they matter is git's own. Tracked files are never reported as
/// ignored, which is what `check-ignore` does by default and what we want.
pub fn ignored_paths(root: &Path, paths: &[String]) -> HashSet<String> {
    let mut out = HashSet::new();
    let Some(stdout) = git_over_stdin(root, &["check-ignore", "--stdin", "-z"], paths) else {
        return out;
    };
    for field in stdout.split(|&b| b == 0) {
        if field.is_empty() {
            continue;
        }
        out.insert(String::from_utf8_lossy(field).into_owned());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lockfiles_and_generated_suffixes_are_artefacts() {
        let f = Filter::new();
        for p in ["Cargo.lock", "web/pnpm-lock.yaml", "api/service.pb.go", "dist/app.min.js"] {
            assert!(matches!(f.classify(p), Verdict::Artefact(_)), "{p} should be an artefact");
        }
    }

    #[test]
    fn source_is_kept() {
        let f = Filter::new();
        for p in ["src/main.rs", "web/src/renderer/scene.ts", "tsconfig.json", "README.md"] {
            assert_eq!(f.classify(p), Verdict::Keep, "{p} should be kept");
        }
    }

    #[test]
    fn vector_graphics_use_the_lower_limit() {
        let f = Filter::new();
        // A generated plot.
        assert!(matches!(
            f.classify_sized("static/plots/step_response.svg", 4_200),
            Verdict::Artefact(Reason::LargeDataFile)
        ));
        // A hand-written icon, which is the case the limit protects.
        assert_eq!(f.classify_sized("web/assets/logo.svg", 18), Verdict::Keep);
    }

    #[test]
    fn json_is_judged_by_size_not_extension() {
        let f = Filter::new();
        // The case this rule exists for.
        assert!(matches!(
            f.classify_sized("static/pathsim/v0.25.0/api.json", 28_751),
            Verdict::Artefact(Reason::LargeDataFile)
        ));
        // The case it must not catch.
        assert_eq!(f.classify_sized("tsconfig.json", 24), Verdict::Keep);
    }

    #[test]
    fn explicit_include_beats_every_heuristic() {
        let mut f = Filter::new();
        f.include("schema/api.json");
        assert_eq!(f.classify_sized("schema/api.json", 90_000), Verdict::Keep);
        f.generated.insert("schema/api.json".into());
        assert_eq!(f.classify("schema/api.json"), Verdict::Keep);
    }

    #[test]
    fn exclude_matches_a_directory_prefix() {
        let mut f = Filter::new();
        f.exclude("vendor");
        assert!(matches!(f.classify("vendor/lib/thing.c"), Verdict::Artefact(_)));
        // Not a prefix of a different directory with the same start.
        assert_eq!(f.classify("vendored/lib.c"), Verdict::Keep);
    }

    #[test]
    fn the_toggle_turns_everything_back_on() {
        let mut f = Filter::new();
        assert!(!f.keep(Path::new("."), "Cargo.lock"));
        f.show_artefacts = true;
        assert!(f.keep(Path::new("."), "Cargo.lock"));
    }
}

#[cfg(test)]
mod ignore_tests {
    use super::*;

    #[test]
    fn git_reports_ignored_paths_and_leaves_tracked_ones() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap().parent().unwrap();
        if !root.join(".git").exists() {
            return; // A source tarball rather than a checkout.
        }
        let probe = vec![
            "target/debug/whatever".to_string(),
            "crates/sanity-core/src/filter.rs".to_string(),
        ];
        let ignored = ignored_paths(root, &probe);
        assert!(ignored.contains("target/debug/whatever"), "target should be ignored");
        assert!(!ignored.contains("crates/sanity-core/src/filter.rs"), "source is not ignored");
    }

    #[test]
    fn an_empty_list_asks_git_nothing() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        assert!(ignored_paths(root, &[]).is_empty());
    }
}
