//! Files that are pictures rather than text: what they are and how big.
//!
//! These used to be skipped. `read_file` returned an empty payload for
//! anything with a NUL byte in it and the shell counted it, so on pathsim the
//! 47 PNG files git lists were 0 of the 328 entries the canvas drew. A
//! repository's images are part of its shape, and for a monitor they are part
//! of what changes: a plot regenerated by a build is exactly the kind of thing
//! worth seeing land.
//!
//! What is read here is only the header. Pixel dimensions are what a panel
//! needs to be sized and shaped, and they sit in the first few dozen bytes of
//! every format that matters. Decoding the picture itself belongs to the
//! renderer, per level of detail, see issue #20.

/// A file that is a picture, and what the layout needs to know about it.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Media {
    /// Pixel dimensions. Zero for a vector image whose header says nothing
    /// useful, which the layout treats as "square, unknown size".
    Image { w: u32, h: u32 },
    /// A document: how many pages, and how big one is in points, as the page
    /// is displayed rather than as it is stored. `pages` is 0 only when
    /// nothing in the file answers, which none of the documents measured so
    /// far did; see `pdf` below.
    Document { pages: u32, w: u32, h: u32 },
}

impl Media {
    /// Aspect as width over height, or 1 when nothing said.
    pub fn aspect(&self) -> f32 {
        match self {
            Media::Image { w, h } | Media::Document { w, h, .. } if *w > 0 && *h > 0 => {
                *w as f32 / *h as f32
            }
            // A page with no size of its own is drawn as A4.
            Media::Document { .. } => 595.0 / 842.0,
            _ => 1.0,
        }
    }

    /// Area for sizing a panel against the text files around it: pixels for
    /// an image, points times pages for a document, which puts an A4 page at
    /// half a megapixel and a 100 page report where a large source file is.
    pub fn pixels(&self) -> u64 {
        match self {
            Media::Image { w, h } => (*w as u64).max(1) * (*h as u64).max(1),
            Media::Document { pages, w, h } => {
                let page = (*w as u64).max(1) * (*h as u64).max(1);
                let page = if *w == 0 || *h == 0 { 595 * 842 } else { page };
                page * (*pages as u64).max(1)
            }
        }
    }
}

/// Whether this path is one we read as a picture at all. By extension, since
/// that is what decides how the bytes are meant to be read.
pub fn is_media(rel: &str) -> bool {
    matches!(
        extension(rel).as_deref(),
        Some("png" | "jpg" | "jpeg" | "gif" | "webp" | "bmp" | "ico" | "svg" | "pdf")
    )
}

fn extension(rel: &str) -> Option<String> {
    let name = rel.rsplit('/').next()?;
    let dot = name.rfind('.')?;
    if dot == 0 {
        return None;
    }
    Some(name[dot + 1..].to_ascii_lowercase())
}

/// Read what the header says. `None` when the file is not a picture, or when
/// its header is not one we can read, in which case the caller keeps treating
/// it as it did before rather than inventing a size.
pub fn probe(rel: &str, bytes: &[u8]) -> Option<Media> {
    match extension(rel).as_deref()? {
        "png" => png(bytes),
        "gif" => gif(bytes),
        "jpg" | "jpeg" => jpeg(bytes),
        "webp" => webp(bytes),
        "bmp" => bmp(bytes),
        "svg" => svg(bytes),
        // The page count needs a parser, not a header. Until then a PDF is
        // one page, which is honest about what we know and still puts the file
        // on the canvas.
        "pdf" => pdf(bytes),
        // An icon file holds several sizes; the first entry's is enough.
        "ico" => ico(bytes),
        _ => None,
    }
}

fn be32(b: &[u8], at: usize) -> u32 {
    u32::from_be_bytes([b[at], b[at + 1], b[at + 2], b[at + 3]])
}

fn png(b: &[u8]) -> Option<Media> {
    if b.len() < 24 || !b.starts_with(&[0x89, b'P', b'N', b'G', 0x0d, 0x0a, 0x1a, 0x0a]) {
        return None;
    }
    Some(Media::Image { w: be32(b, 16), h: be32(b, 20) })
}

fn gif(b: &[u8]) -> Option<Media> {
    if b.len() < 10 || !b.starts_with(b"GIF8") {
        return None;
    }
    Some(Media::Image {
        w: u16::from_le_bytes([b[6], b[7]]) as u32,
        h: u16::from_le_bytes([b[8], b[9]]) as u32,
    })
}

/// JPEG keeps its size in a start-of-frame marker, which sits after however
/// many other segments the encoder felt like writing, so the segments are
/// walked.
fn jpeg(b: &[u8]) -> Option<Media> {
    if b.len() < 4 || b[0] != 0xff || b[1] != 0xd8 {
        return None;
    }
    let mut i = 2;
    while i + 9 < b.len() {
        if b[i] != 0xff {
            i += 1;
            continue;
        }
        let marker = b[i + 1];
        // Start of frame, any of the flavours, but not the restart or
        // arithmetic-coding markers that share the range.
        if (0xc0..=0xcf).contains(&marker) && !matches!(marker, 0xc4 | 0xc8 | 0xcc) {
            let h = u16::from_be_bytes([b[i + 5], b[i + 6]]) as u32;
            let w = u16::from_be_bytes([b[i + 7], b[i + 8]]) as u32;
            return Some(Media::Image { w, h });
        }
        let len = u16::from_be_bytes([b[i + 2], b[i + 3]]) as usize;
        if len < 2 {
            return None;
        }
        i += 2 + len;
    }
    None
}

fn webp(b: &[u8]) -> Option<Media> {
    if b.len() < 30 || !b.starts_with(b"RIFF") || &b[8..12] != b"WEBP" {
        return None;
    }
    match &b[12..16] {
        // Lossy: the size is in the VP8 frame header, 14 bits each.
        b"VP8 " => {
            let w = u16::from_le_bytes([b[26], b[27]]) as u32 & 0x3fff;
            let h = u16::from_le_bytes([b[28], b[29]]) as u32 & 0x3fff;
            Some(Media::Image { w, h })
        }
        // Lossless: 14 bits each, minus one, packed across four bytes.
        b"VP8L" => {
            let bits = u32::from_le_bytes([b[21], b[22], b[23], b[24]]);
            Some(Media::Image { w: (bits & 0x3fff) + 1, h: ((bits >> 14) & 0x3fff) + 1 })
        }
        // Extended: canvas size, 24 bits each, minus one.
        b"VP8X" => {
            let w = u32::from_le_bytes([b[24], b[25], b[26], 0]) + 1;
            let h = u32::from_le_bytes([b[27], b[28], b[29], 0]) + 1;
            Some(Media::Image { w, h })
        }
        _ => None,
    }
}

fn bmp(b: &[u8]) -> Option<Media> {
    if b.len() < 26 || !b.starts_with(b"BM") {
        return None;
    }
    let w = i32::from_le_bytes([b[18], b[19], b[20], b[21]]);
    let h = i32::from_le_bytes([b[22], b[23], b[24], b[25]]);
    Some(Media::Image { w: w.unsigned_abs(), h: h.unsigned_abs() })
}

fn ico(b: &[u8]) -> Option<Media> {
    if b.len() < 8 || b[0] != 0 || b[1] != 0 || b[2] != 1 {
        return None;
    }
    // 0 in the header means 256, which is the one place this format is cute.
    let side = |v: u8| if v == 0 { 256 } else { v as u32 };
    Some(Media::Image { w: side(b[6]), h: side(b[7]) })
}

/// SVG is text, so its size is whatever its root element claims: a width and
/// a height in absolute units, or the viewBox, which is the case for most
/// icons, or one of the two and the viewBox's proportion for the other.
///
/// Only the root `<svg>` tag's own attributes, by their whole names. Looking
/// for the first `width=` anywhere in the head of the file, which is what this
/// did first, found `stroke-width="1.6"` in an icon set and a child `<rect
/// width="51" height="447">` in a 3:1 logo, and each panel came out in the
/// proportion of whatever it had found, with the drawing stretched into it.
fn svg(b: &[u8]) -> Option<Media> {
    let head = String::from_utf8_lossy(&b[..b.len().min(8192)]);
    let attrs = root_attributes(&head, "svg")?;
    let get = |name: &str| attrs.iter().find(|(n, _)| n == name).map(|(_, v)| v.as_str());
    let width = get("width").and_then(svg_length);
    let height = get("height").and_then(svg_length);
    let view: Option<(f32, f32)> = get("viewBox").and_then(|v| {
        let n: Vec<f32> = v.split([' ', ',', '\t', '\n', '\r']).filter_map(|s| s.trim().parse().ok()).collect();
        (n.len() == 4 && n[2] > 0.0 && n[3] > 0.0).then(|| (n[2], n[3]))
    });
    let (w, h) = match (width, height, view) {
        (Some(w), Some(h), _) => (w, h),
        (Some(w), None, Some((vw, vh))) => (w, w * vh / vw),
        (None, Some(h), Some((vw, vh))) => (h * vw / vh, h),
        (_, _, Some(v)) => v,
        _ => return None,
    };
    (w > 0.0 && h > 0.0).then(|| Media::Image { w: (w.round() as u32).max(1), h: (h.round() as u32).max(1) })
}

/// A length in an SVG attribute, in CSS pixels, when it is an absolute one.
/// A percentage, or a size relative to a font, is a size only in a page that
/// holds the drawing, which this is not.
fn svg_length(v: &str) -> Option<f32> {
    let v = v.trim();
    let split = v.find(|c: char| !(c.is_ascii_digit() || c == '.' || c == '-' || c == '+' || c == 'e' || c == 'E'))
        .unwrap_or(v.len());
    // `e` belongs to the number only when a digit follows; `em` is a unit.
    let split = if v[..split].ends_with(['e', 'E']) { split - 1 } else { split };
    let n: f32 = v[..split].parse().ok()?;
    let per = match v[split..].trim() {
        "" | "px" => 1.0,
        "pt" => 4.0 / 3.0,
        "pc" => 16.0,
        "mm" => 96.0 / 25.4,
        "cm" => 96.0 / 2.54,
        "in" => 96.0,
        _ => return None,
    };
    (n > 0.0).then_some(n * per)
}

/// The attributes of the first `<name ...>` tag in `text`, as written: past
/// the XML declaration, comments and a doctype, since those are not tags of
/// that name. Quotes are respected, so a `>` inside a value does not end it.
fn root_attributes(text: &str, name: &str) -> Option<Vec<(String, String)>> {
    let open = format!("<{name}");
    let mut from = 0;
    let start = loop {
        let at = from + text[from..].find(&open)?;
        // Inside a comment it is not a tag: go on after the comment.
        if let Some(c) = text[from..at].rfind("<!--").map(|c| from + c) {
            if !text[c..at].contains("-->") {
                from = c + text[c..].find("-->")? + 3;
                continue;
            }
        }
        let next = text[at + open.len()..].chars().next()?;
        if next.is_whitespace() || next == '>' || next == '/' {
            break at + open.len();
        }
        from = at + open.len();
    };
    let body = &text[start..];
    let mut out = Vec::new();
    let mut chars = body.char_indices().peekable();
    loop {
        while matches!(chars.peek(), Some((_, c)) if c.is_whitespace()) {
            chars.next();
        }
        let (at, c) = chars.next()?;
        if c == '>' || c == '/' {
            return Some(out);
        }
        let mut end = at + c.len_utf8();
        while let Some(&(i, c)) = chars.peek() {
            if c == '=' || c.is_whitespace() || c == '>' || c == '/' {
                break;
            }
            end = i + c.len_utf8();
            chars.next();
        }
        let key = body[at..end].to_string();
        while matches!(chars.peek(), Some((_, c)) if c.is_whitespace()) {
            chars.next();
        }
        if !matches!(chars.peek(), Some((_, '='))) {
            out.push((key, String::new()));
            continue;
        }
        chars.next();
        while matches!(chars.peek(), Some((_, c)) if c.is_whitespace()) {
            chars.next();
        }
        let (q_at, q) = chars.next()?;
        let value = if q == '"' || q == '\'' {
            let from = q_at + 1;
            let mut to = body.len();
            for (i, c) in chars.by_ref() {
                if c == q {
                    to = i;
                    break;
                }
            }
            body[from..to].to_string()
        } else {
            let mut to = q_at + q.len_utf8();
            while let Some(&(i, c)) = chars.peek() {
                if c.is_whitespace() || c == '>' {
                    break;
                }
                to = i + c.len_utf8();
                chars.next();
            }
            body[q_at..to].to_string()
        };
        out.push((key, value));
    }
}

/// A PDF's page count and page size, read out of the file as it is written.
///
/// Not with a PDF library: reading two numbers is not worth twenty crates of
/// dependency, several of them cryptography. So the page tree is looked for in
/// the clear, which is where most writers leave it.
///
/// Measured against `pdfinfo` over 25 real documents, papers, reports, a
/// habilitation thesis, a slide deck, plots from matplotlib: 25 of 25 exact
/// on both the page count and the page size. Three of them keep the page tree
/// in a compressed object stream and one is 16:9, which is why the two extra
/// passes below exist: without them a slide deck came back as 0 by 0 and was
/// drawn as A4, which is the wrong shape for every panel it has.
///
/// The one trap, which cost the first version five of those documents: the
/// outline tree carries a `/Count` of its own, so a seven page paper with
/// eleven bookmarks measured eleven pages. Only a `/Count` inside an object
/// that says `/Type /Pages` is a page count.
fn pdf(b: &[u8]) -> Option<Media> {
    if !b.starts_with(b"%PDF-") {
        return None;
    }
    let mut pages = page_count(b);
    let mut size = media_box(b);
    let mut turn = rotation(b);
    // Nothing in the clear: inflate the object streams and look again. A
    // slide deck written by a tool that compresses its page tree used to come
    // back as 0 by 0, and a panel with no size of its own is drawn as A4,
    // which is exactly the wrong shape for 16:9.
    if pages == 0 || size.is_none() {
        let inflated = inflate_object_streams(b, INFLATE_BUDGET);
        if !inflated.is_empty() {
            if pages == 0 {
                pages = page_count(&inflated);
            }
            if size.is_none() {
                size = media_box(&inflated);
            }
            if turn == 0 {
                turn = rotation(&inflated);
            }
        }
    }
    let (w, h) = size.unwrap_or((0, 0));
    // A page can be stored upright and displayed on its side. Readers apply
    // `/Rotate` before anything is shown, so the size that matters for a panel
    // is the rotated one.
    let (w, h) = if turn == 90 || turn == 270 { (h, w) } else { (w, h) };
    Some(Media::Document { pages, w, h })
}

/// How much of a file is inflated while looking for its page tree. Two
/// megabytes is several times the object streams of the documents this was
/// measured on, and stops a pathological file from turning into a scan of
/// itself.
const INFLATE_BUDGET: usize = 2 * 1024 * 1024;

/// How far back from a `stream` keyword its dictionary is looked for.
const DICT_LOOKBACK: usize = 400;

/// The object streams in a PDF, inflated and concatenated, up to `budget`.
///
/// Only the streams whose dictionary says `/ObjStm`: those are the ones the
/// page tree hides in when it is not in the clear. Measured on a 103 page
/// paper of 2.9 MB: 1712 streams in the file, 856 of them inflatable, 17
/// object streams, and the page tree is in one of those. Inflating everything
/// took the budget before it got there; inflating the seventeen finds it.
///
/// The result is not a PDF and is not treated as one. It is a haystack for
/// the same two needles the uncompressed path looks for.
fn inflate_object_streams(b: &[u8], budget: usize) -> Vec<u8> {
    use std::io::Read;
    let mut out: Vec<u8> = Vec::new();
    let mut at = 0usize;
    while let Some(found) = find(b, b"stream", at) {
        at = found + 6;
        let from = found.saturating_sub(DICT_LOOKBACK);
        if find(&b[from..found], b"/ObjStm", 0).is_none() {
            continue;
        }
        let mut start = at;
        while start < b.len() && (b[start] == b'\r' || b[start] == b'\n') {
            start += 1;
        }
        let end = find(b, b"endstream", start).unwrap_or(b.len());
        if end <= start {
            continue;
        }
        let mut buf = Vec::new();
        let room = budget.saturating_sub(out.len()) as u64;
        if flate2::read::ZlibDecoder::new(&b[start..end])
            .take(room)
            .read_to_end(&mut buf)
            .is_ok()
        {
            out.extend_from_slice(&buf);
        }
        at = end + 9;
        if out.len() >= budget || (media_box(&out).is_some() && page_count(&out) > 0) {
            break;
        }
    }
    out
}

/// `/Rotate`, normalised to 0, 90, 180 or 270. The first one in the file: it
/// is inherited from the page tree unless a page overrides it, and a document
/// whose pages disagree is not one a single panel can describe anyway.
fn rotation(b: &[u8]) -> u32 {
    let Some(at) = find(b, b"/Rotate", 0) else { return 0 };
    let rest = &b[at + 7..b.len().min(at + 7 + 16)];
    let text = String::from_utf8_lossy(rest);
    let text = text.trim_start();
    let negative = text.starts_with('-');
    let digits: String = text
        .trim_start_matches('-')
        .chars()
        .take_while(|c| c.is_ascii_digit())
        .collect();
    let Ok(value) = digits.parse::<i32>() else { return 0 };
    let value = if negative { -value } else { value };
    (((value % 360) + 360) % 360) as u32
}

fn page_count(b: &[u8]) -> u32 {
    let mut best = 0u32;
    let mut at = 0usize;
    while let Some(found) = find(b, b"/Type", at) {
        at = found + 5;
        let rest = &b[at..b.len().min(at + 16)];
        let after = rest.iter().position(|c| !c.is_ascii_whitespace()).unwrap_or(0);
        if !rest[after..].starts_with(b"/Pages") {
            continue;
        }
        // The object this appears in, so a `/Count` from anywhere else cannot
        // be read as a page count.
        let start = rfind(b, b"obj", found).unwrap_or(found);
        let end = find(b, b"endobj", found).unwrap_or(b.len().min(found + 2048));
        if let Some(count) = number_after(&b[start..end], b"/Count") {
            best = best.max(count);
        }
    }
    if best > 0 {
        return best;
    }
    // No page tree in the clear. Counting page objects is the fallback, and
    // 0 when there are none of those either.
    let mut pages = 0u32;
    let mut at = 0usize;
    while let Some(found) = find(b, b"/Type", at) {
        at = found + 5;
        let rest = &b[at..b.len().min(at + 16)];
        let after = rest.iter().position(|c| !c.is_ascii_whitespace()).unwrap_or(0);
        let tail = &rest[after..];
        if tail.starts_with(b"/Page") && !tail.starts_with(b"/Pages") {
            pages += 1;
        }
    }
    pages
}

/// Width and height in points, from the first `/MediaBox`. Documents whose
/// pages differ in size are rare enough that the first one stands for all.
fn media_box(b: &[u8]) -> Option<(u32, u32)> {
    let at = find(b, b"/MediaBox", 0)?;
    let rest = &b[at + 9..b.len().min(at + 80)];
    let open = rest.iter().position(|&c| c == b'[')?;
    let close = rest.iter().position(|&c| c == b']')?;
    if close < open {
        return None;
    }
    let nums: Vec<f32> = String::from_utf8_lossy(&rest[open + 1..close])
        .split_whitespace()
        .filter_map(|s| s.parse().ok())
        .collect();
    if nums.len() != 4 {
        return None;
    }
    let w = (nums[2] - nums[0]).abs().round();
    let h = (nums[3] - nums[1]).abs().round();
    if w < 1.0 || h < 1.0 {
        return None;
    }
    Some((w as u32, h as u32))
}

fn number_after(b: &[u8], key: &[u8]) -> Option<u32> {
    let at = find(b, key, 0)? + key.len();
    let rest = &b[at..b.len().min(at + 24)];
    let text = String::from_utf8_lossy(rest);
    let digits: String = text.trim_start().chars().take_while(|c| c.is_ascii_digit()).collect();
    digits.parse().ok()
}

fn find(haystack: &[u8], needle: &[u8], from: usize) -> Option<usize> {
    if from >= haystack.len() {
        return None;
    }
    haystack[from..]
        .windows(needle.len())
        .position(|w| w == needle)
        .map(|p| p + from)
}

fn rfind(haystack: &[u8], needle: &[u8], before: usize) -> Option<usize> {
    haystack[..before.min(haystack.len())]
        .windows(needle.len())
        .rposition(|w| w == needle)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_png_header_gives_its_size() {
        let mut b = vec![0x89, b'P', b'N', b'G', 0x0d, 0x0a, 0x1a, 0x0a];
        b.extend_from_slice(&[0, 0, 0, 13]);
        b.extend_from_slice(b"IHDR");
        b.extend_from_slice(&3570u32.to_be_bytes());
        b.extend_from_slice(&2369u32.to_be_bytes());
        assert_eq!(probe("a/plot.png", &b), Some(Media::Image { w: 3570, h: 2369 }));
    }

    #[test]
    fn a_jpeg_is_walked_to_its_start_of_frame() {
        // SOI, an APP0 segment to step over, then SOF0 with the size in it.
        let mut b = vec![0xff, 0xd8, 0xff, 0xe0, 0x00, 0x04, 0x00, 0x00];
        b.extend_from_slice(&[0xff, 0xc0, 0x00, 0x11, 0x08]);
        b.extend_from_slice(&600u16.to_be_bytes()); // height first
        b.extend_from_slice(&800u16.to_be_bytes());
        b.extend_from_slice(&[0; 8]);
        assert_eq!(probe("x.jpg", &b), Some(Media::Image { w: 800, h: 600 }));
    }

    #[test]
    fn an_svg_is_the_size_its_root_says() {
        let svg = |text: &str| probe("i.svg", text.as_bytes());
        let image = |w, h| Some(Media::Image { w, h });
        assert_eq!(svg(r#"<svg width="64" height="32" xmlns="http://www.w3.org/2000/svg">"#), image(64, 32));
        assert_eq!(svg(r#"<svg viewBox="0 0 24 16" xmlns="http://www.w3.org/2000/svg">"#), image(24, 16));
        // Absolute units in pixels, and the proportion kept.
        assert_eq!(svg(r#"<svg width="210mm" height="297mm">"#), image(794, 1123));
        assert_eq!(svg(r#"<svg width="460.8pt" height="345.6pt" viewBox="0 0 460.8 345.6">"#), image(614, 461));
        // A relative size is no size: the viewBox.
        assert_eq!(svg(r#"<svg width="100%" height="100%" viewBox="0 0 300 100">"#), image(300, 100));
        // One side given, the other from the viewBox's proportion.
        assert_eq!(svg(r#"<svg width="48" viewBox="0 0 96 64">"#), image(48, 32));
        // Not the stroke's width, and not a child's: both of these were
        // read as the drawing's size.
        assert_eq!(
            svg(r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 64" fill="none" stroke-width="1.6"><rect width="52" height="40"/></svg>"#),
            image(96, 64),
        );
        assert_eq!(
            svg(r#"<svg viewBox="0 0 1354 451"><g><rect x="3232" y="966" width="51.0002" height="447"/></g></svg>"#),
            image(1354, 451),
        );
        // Past a declaration and a comment, and a `>` inside a value.
        assert_eq!(
            svg("<?xml version=\"1.0\"?>\n<!-- <svg width=\"1\" height=\"1\"> -->\n<svg data-x=\"a>b\" width='40' height='20'>"),
            image(40, 20),
        );
        assert_eq!(svg("<svgx width=\"4\" height=\"4\">"), None);
    }

    #[test]
    fn what_is_not_a_picture_is_left_alone() {
        assert_eq!(probe("main.rs", b"fn main() {}"), None);
        assert_eq!(probe("x.png", b"not a png"), None);
        assert!(is_media("docs/a.PNG"));
        assert!(is_media("paper.pdf"));
        assert!(!is_media("main.rs"));
        assert!(!is_media(".gitignore"));
    }

    #[test]
    fn a_pdf_reports_its_pages_and_page_size() {
        let doc = b"%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n\
                    2 0 obj\n<< /Type /Pages /Count 42 /Kids [3 0 R] >>\nendobj\n\
                    3 0 obj\n<< /Type /Page /MediaBox [0 0 595 842] >>\nendobj\n";
        assert_eq!(probe("p.pdf", doc), Some(Media::Document { pages: 42, w: 595, h: 842 }));
    }

    // A page stored upright and displayed on its side. Readers apply
    // `/Rotate` before anything is drawn, so a panel that ignores it is the
    // wrong shape for every scanned landscape page there is.
    #[test]
    fn a_rotated_page_is_as_wide_as_it_is_displayed() {
        let upright = b"%PDF-1.4\n<< /Type /Pages /Count 1 /MediaBox [0 0 595 842] >>\n";
        let turned =
            b"%PDF-1.4\n<< /Type /Pages /Count 1 /MediaBox [0 0 595 842] /Rotate 90 >>\n";
        assert_eq!(probe("a.pdf", upright), Some(Media::Document { pages: 1, w: 595, h: 842 }));
        assert_eq!(probe("a.pdf", turned), Some(Media::Document { pages: 1, w: 842, h: 595 }));
        let back =
            b"%PDF-1.4\n<< /Type /Pages /Count 1 /MediaBox [0 0 595 842] /Rotate -90 >>\n";
        assert_eq!(probe("a.pdf", back), Some(Media::Document { pages: 1, w: 842, h: 595 }));
        let half =
            b"%PDF-1.4\n<< /Type /Pages /Count 1 /MediaBox [0 0 595 842] /Rotate 180 >>\n";
        assert_eq!(probe("a.pdf", half), Some(Media::Document { pages: 1, w: 595, h: 842 }));
    }

    // The page tree inside a compressed object stream, which is what a third
    // of real PDFs do and what left a 16:9 slide deck being drawn as A4.
    #[test]
    fn a_page_tree_in_an_object_stream_is_read() {
        use std::io::Write;
        let inner = b"<</Type/Pages/Count 25/MediaBox[0 0 454 255]>>";
        let mut encoder =
            flate2::write::ZlibEncoder::new(Vec::new(), flate2::Compression::default());
        encoder.write_all(inner).unwrap();
        let packed = encoder.finish().unwrap();

        let mut pdf: Vec<u8> = Vec::new();
        pdf.extend_from_slice(b"%PDF-1.5\n1 0 obj\n<< /Type /ObjStm /N 1 /Filter /FlateDecode >>\nstream\n");
        pdf.extend_from_slice(&packed);
        pdf.extend_from_slice(b"\nendstream\nendobj\n");
        assert_eq!(
            probe("deck.pdf", &pdf),
            Some(Media::Document { pages: 25, w: 454, h: 255 }),
        );
    }

    #[test]
    fn an_outlines_count_is_not_a_page_count() {
        // What cost five of the twenty five documents I measured against.
        let doc = b"%PDF-1.4\n1 0 obj\n<< /Type /Outlines /Count 11 >>\nendobj\n\
                    2 0 obj\n<< /Type /Pages /Count 7 /Kids [3 0 R] >>\nendobj\n\
                    3 0 obj\n<< /Type /Page /MediaBox [0 0 612 792] >>\nendobj\n";
        assert_eq!(probe("p.pdf", doc), Some(Media::Document { pages: 7, w: 612, h: 792 }));
    }

    #[test]
    fn a_pdf_that_hides_its_page_tree_says_it_does_not_know() {
        // Everything in an object stream, which is a third of the PDFs I have.
        let doc = b"%PDF-1.5\n4 0 obj\n<< /Type /ObjStm /N 12 /Length 900 >>\nstream\n\
                    (compressed)\nendstream\nendobj\n";
        assert_eq!(probe("p.pdf", doc), Some(Media::Document { pages: 0, w: 0, h: 0 }));
        // And is still sized as one A4 page rather than as nothing.
        let m = Media::Document { pages: 0, w: 0, h: 0 };
        assert_eq!(m.pixels(), 595 * 842);
        assert!((m.aspect() - 595.0 / 842.0).abs() < 1e-6);
    }

    #[test]
    fn size_and_shape_come_out_of_the_header() {
        let wide = Media::Image { w: 1600, h: 900 };
        assert!((wide.aspect() - 16.0 / 9.0).abs() < 1e-6);
        assert_eq!(wide.pixels(), 1_440_000);
        // A page is portrait, and three pages are three times the area.
        let doc = Media::Document { pages: 3, w: 595, h: 842 };
        assert!(doc.aspect() < 1.0);
        assert_eq!(doc.pixels(), 3 * 595 * 842);
        // Nothing useful in the header is a square of unknown size.
        assert_eq!(Media::Image { w: 0, h: 0 }.aspect(), 1.0);
    }
}
