//! Files that are pictures rather than text: what they are and how big.
//!
//! These used to be skipped. `read_file` returned an empty payload for
//! anything with a NUL byte in it and the shell counted it, so on pathsim the
//! 47 PNG files git lists were 0 of the 328 entries the canvas drew. A
//! repository's images are part of its shape, and for a monitor they are part
//! of what changes: a plot regenerated by a build is exactly the kind of thing
//! worth seeing land.
//!
//! What is read here is only the header. Pixel dimensions are what a panel
//! needs to be sized and shaped, and they sit in the first few dozen bytes of
//! every format that matters. Decoding the picture itself belongs to the
//! renderer, per level of detail, see issue #20.

/// A file that is a picture, and what the layout needs to know about it.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Media {
    /// Pixel dimensions. Zero for a vector image whose header says nothing
    /// useful, which the layout treats as "square, unknown size".
    Image { w: u32, h: u32 },
    /// A document: how many pages, and how big one is in points. `pages` is
    /// 0 when the file keeps its page tree in a compressed object stream,
    /// which is a third of the PDFs I have; see `pdf` below.
    Document { pages: u32, w: u32, h: u32 },
}

impl Media {
    /// Aspect as width over height, or 1 when nothing said.
    pub fn aspect(&self) -> f32 {
        match self {
            Media::Image { w, h } | Media::Document { w, h, .. } if *w > 0 && *h > 0 => {
                *w as f32 / *h as f32
            }
            // A page with no size of its own is drawn as A4.
            Media::Document { .. } => 595.0 / 842.0,
            _ => 1.0,
        }
    }

    /// Area for sizing a panel against the text files around it: pixels for
    /// an image, points times pages for a document, which puts an A4 page at
    /// half a megapixel and a 100 page report where a large source file is.
    pub fn pixels(&self) -> u64 {
        match self {
            Media::Image { w, h } => (*w as u64).max(1) * (*h as u64).max(1),
            Media::Document { pages, w, h } => {
                let page = (*w as u64).max(1) * (*h as u64).max(1);
                let page = if *w == 0 || *h == 0 { 595 * 842 } else { page };
                page * (*pages as u64).max(1)
            }
        }
    }
}

/// Whether this path is one we read as a picture at all. By extension, since
/// that is what decides how the bytes are meant to be read.
pub fn is_media(rel: &str) -> bool {
    matches!(
        extension(rel).as_deref(),
        Some("png" | "jpg" | "jpeg" | "gif" | "webp" | "bmp" | "ico" | "svg" | "pdf")
    )
}

fn extension(rel: &str) -> Option<String> {
    let name = rel.rsplit('/').next()?;
    let dot = name.rfind('.')?;
    if dot == 0 {
        return None;
    }
    Some(name[dot + 1..].to_ascii_lowercase())
}

/// Read what the header says. `None` when the file is not a picture, or when
/// its header is not one we can read, in which case the caller keeps treating
/// it as it did before rather than inventing a size.
pub fn probe(rel: &str, bytes: &[u8]) -> Option<Media> {
    match extension(rel).as_deref()? {
        "png" => png(bytes),
        "gif" => gif(bytes),
        "jpg" | "jpeg" => jpeg(bytes),
        "webp" => webp(bytes),
        "bmp" => bmp(bytes),
        "svg" => svg(bytes),
        // The page count needs a parser, not a header. Until then a PDF is
        // one page, which is honest about what we know and still puts the file
        // on the canvas.
        "pdf" => pdf(bytes),
        // An icon file holds several sizes; the first entry's is enough.
        "ico" => ico(bytes),
        _ => None,
    }
}

fn be32(b: &[u8], at: usize) -> u32 {
    u32::from_be_bytes([b[at], b[at + 1], b[at + 2], b[at + 3]])
}

fn png(b: &[u8]) -> Option<Media> {
    if b.len() < 24 || !b.starts_with(&[0x89, b'P', b'N', b'G', 0x0d, 0x0a, 0x1a, 0x0a]) {
        return None;
    }
    Some(Media::Image { w: be32(b, 16), h: be32(b, 20) })
}

fn gif(b: &[u8]) -> Option<Media> {
    if b.len() < 10 || !b.starts_with(b"GIF8") {
        return None;
    }
    Some(Media::Image {
        w: u16::from_le_bytes([b[6], b[7]]) as u32,
        h: u16::from_le_bytes([b[8], b[9]]) as u32,
    })
}

/// JPEG keeps its size in a start-of-frame marker, which sits after however
/// many other segments the encoder felt like writing, so the segments are
/// walked.
fn jpeg(b: &[u8]) -> Option<Media> {
    if b.len() < 4 || b[0] != 0xff || b[1] != 0xd8 {
        return None;
    }
    let mut i = 2;
    while i + 9 < b.len() {
        if b[i] != 0xff {
            i += 1;
            continue;
        }
        let marker = b[i + 1];
        // Start of frame, any of the flavours, but not the restart or
        // arithmetic-coding markers that share the range.
        if (0xc0..=0xcf).contains(&marker) && !matches!(marker, 0xc4 | 0xc8 | 0xcc) {
            let h = u16::from_be_bytes([b[i + 5], b[i + 6]]) as u32;
            let w = u16::from_be_bytes([b[i + 7], b[i + 8]]) as u32;
            return Some(Media::Image { w, h });
        }
        let len = u16::from_be_bytes([b[i + 2], b[i + 3]]) as usize;
        if len < 2 {
            return None;
        }
        i += 2 + len;
    }
    None
}

fn webp(b: &[u8]) -> Option<Media> {
    if b.len() < 30 || !b.starts_with(b"RIFF") || &b[8..12] != b"WEBP" {
        return None;
    }
    match &b[12..16] {
        // Lossy: the size is in the VP8 frame header, 14 bits each.
        b"VP8 " => {
            let w = u16::from_le_bytes([b[26], b[27]]) as u32 & 0x3fff;
            let h = u16::from_le_bytes([b[28], b[29]]) as u32 & 0x3fff;
            Some(Media::Image { w, h })
        }
        // Lossless: 14 bits each, minus one, packed across four bytes.
        b"VP8L" => {
            let bits = u32::from_le_bytes([b[21], b[22], b[23], b[24]]);
            Some(Media::Image { w: (bits & 0x3fff) + 1, h: ((bits >> 14) & 0x3fff) + 1 })
        }
        // Extended: canvas size, 24 bits each, minus one.
        b"VP8X" => {
            let w = u32::from_le_bytes([b[24], b[25], b[26], 0]) + 1;
            let h = u32::from_le_bytes([b[27], b[28], b[29], 0]) + 1;
            Some(Media::Image { w, h })
        }
        _ => None,
    }
}

fn bmp(b: &[u8]) -> Option<Media> {
    if b.len() < 26 || !b.starts_with(b"BM") {
        return None;
    }
    let w = i32::from_le_bytes([b[18], b[19], b[20], b[21]]);
    let h = i32::from_le_bytes([b[22], b[23], b[24], b[25]]);
    Some(Media::Image { w: w.unsigned_abs(), h: h.unsigned_abs() })
}

fn ico(b: &[u8]) -> Option<Media> {
    if b.len() < 8 || b[0] != 0 || b[1] != 0 || b[2] != 1 {
        return None;
    }
    // 0 in the header means 256, which is the one place this format is cute.
    let side = |v: u8| if v == 0 { 256 } else { v as u32 };
    Some(Media::Image { w: side(b[6]), h: side(b[7]) })
}

/// SVG is text, so its size is whatever the document claims: a width and
/// height if they are in pixels, otherwise the viewBox, which is the case for
/// most icons.
fn svg(b: &[u8]) -> Option<Media> {
    let head = String::from_utf8_lossy(&b[..b.len().min(2048)]);
    let number = |after: &str| -> Option<f32> {
        let at = head.find(after)? + after.len();
        let rest = head[at..].trim_start();
        let rest = rest.strip_prefix(['"', '\''].as_ref()).unwrap_or(rest);
        let end = rest.find(|c: char| !c.is_ascii_digit() && c != '.').unwrap_or(rest.len());
        rest[..end].parse().ok()
    };
    if let (Some(w), Some(h)) = (number("width="), number("height=")) {
        if w > 0.0 && h > 0.0 {
            return Some(Media::Image { w: w as u32, h: h as u32 });
        }
    }
    let at = head.find("viewBox=")? + "viewBox=".len();
    let rest = head[at..].trim_start();
    let rest = rest.strip_prefix(['"', '\''].as_ref()).unwrap_or(rest);
    // Only the attribute's own value: without cutting at the closing quote
    // the last number arrives as `16"` and does not parse, which left three
    // numbers where four are needed.
    let rest = &rest[..rest.find(['"', '\'']).unwrap_or(rest.len())];
    let nums: Vec<f32> = rest
        .split([' ', ','])
        .filter_map(|s| s.trim().parse().ok())
        .take(4)
        .collect();
    if nums.len() == 4 && nums[2] > 0.0 && nums[3] > 0.0 {
        return Some(Media::Image { w: nums[2] as u32, h: nums[3] as u32 });
    }
    None
}

/// A PDF's page count and page size, read out of the file as it is written.
///
/// Not with a PDF library: reading two numbers is not worth twenty crates of
/// dependency, several of them cryptography. So the page tree is looked for in
/// the clear, which is where most writers leave it.
///
/// Measured against `pdfinfo` over 25 real documents, papers, reports, a
/// habilitation thesis, plots from matplotlib: 21 page counts exact, one two
/// too high, three unknown, and every page size that was there at all correct.
/// The three unknowns keep their page tree in a compressed object stream, and
/// for them the count comes back 0 rather than guessed. The renderer will
/// know better once it rasterises a first page, since the platform's own PDF
/// reader hands over the count with it; see issue #21.
///
/// The one trap, which cost the first version five of those documents: the
/// outline tree carries a `/Count` of its own, so a seven page paper with
/// eleven bookmarks measured eleven pages. Only a `/Count` inside an object
/// that says `/Type /Pages` is a page count.
fn pdf(b: &[u8]) -> Option<Media> {
    if !b.starts_with(b"%PDF-") {
        return None;
    }
    let (w, h) = media_box(b).unwrap_or((0, 0));
    Some(Media::Document { pages: page_count(b), w, h })
}

fn page_count(b: &[u8]) -> u32 {
    let mut best = 0u32;
    let mut at = 0usize;
    while let Some(found) = find(b, b"/Type", at) {
        at = found + 5;
        let rest = &b[at..b.len().min(at + 16)];
        let after = rest.iter().position(|c| !c.is_ascii_whitespace()).unwrap_or(0);
        if !rest[after..].starts_with(b"/Pages") {
            continue;
        }
        // The object this appears in, so a `/Count` from anywhere else cannot
        // be read as a page count.
        let start = rfind(b, b"obj", found).unwrap_or(found);
        let end = find(b, b"endobj", found).unwrap_or(b.len().min(found + 2048));
        if let Some(count) = number_after(&b[start..end], b"/Count") {
            best = best.max(count);
        }
    }
    if best > 0 {
        return best;
    }
    // No page tree in the clear. Counting page objects is the fallback, and
    // 0 when there are none of those either.
    let mut pages = 0u32;
    let mut at = 0usize;
    while let Some(found) = find(b, b"/Type", at) {
        at = found + 5;
        let rest = &b[at..b.len().min(at + 16)];
        let after = rest.iter().position(|c| !c.is_ascii_whitespace()).unwrap_or(0);
        let tail = &rest[after..];
        if tail.starts_with(b"/Page") && !tail.starts_with(b"/Pages") {
            pages += 1;
        }
    }
    pages
}

/// Width and height in points, from the first `/MediaBox`. Documents whose
/// pages differ in size are rare enough that the first one stands for all.
fn media_box(b: &[u8]) -> Option<(u32, u32)> {
    let at = find(b, b"/MediaBox", 0)?;
    let rest = &b[at + 9..b.len().min(at + 80)];
    let open = rest.iter().position(|&c| c == b'[')?;
    let close = rest.iter().position(|&c| c == b']')?;
    if close < open {
        return None;
    }
    let nums: Vec<f32> = String::from_utf8_lossy(&rest[open + 1..close])
        .split_whitespace()
        .filter_map(|s| s.parse().ok())
        .collect();
    if nums.len() != 4 {
        return None;
    }
    let w = (nums[2] - nums[0]).abs().round();
    let h = (nums[3] - nums[1]).abs().round();
    if w < 1.0 || h < 1.0 {
        return None;
    }
    Some((w as u32, h as u32))
}

fn number_after(b: &[u8], key: &[u8]) -> Option<u32> {
    let at = find(b, key, 0)? + key.len();
    let rest = &b[at..b.len().min(at + 24)];
    let text = String::from_utf8_lossy(rest);
    let digits: String = text.trim_start().chars().take_while(|c| c.is_ascii_digit()).collect();
    digits.parse().ok()
}

fn find(haystack: &[u8], needle: &[u8], from: usize) -> Option<usize> {
    if from >= haystack.len() {
        return None;
    }
    haystack[from..]
        .windows(needle.len())
        .position(|w| w == needle)
        .map(|p| p + from)
}

fn rfind(haystack: &[u8], needle: &[u8], before: usize) -> Option<usize> {
    haystack[..before.min(haystack.len())]
        .windows(needle.len())
        .rposition(|w| w == needle)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_png_header_gives_its_size() {
        let mut b = vec![0x89, b'P', b'N', b'G', 0x0d, 0x0a, 0x1a, 0x0a];
        b.extend_from_slice(&[0, 0, 0, 13]);
        b.extend_from_slice(b"IHDR");
        b.extend_from_slice(&3570u32.to_be_bytes());
        b.extend_from_slice(&2369u32.to_be_bytes());
        assert_eq!(probe("a/plot.png", &b), Some(Media::Image { w: 3570, h: 2369 }));
    }

    #[test]
    fn a_jpeg_is_walked_to_its_start_of_frame() {
        // SOI, an APP0 segment to step over, then SOF0 with the size in it.
        let mut b = vec![0xff, 0xd8, 0xff, 0xe0, 0x00, 0x04, 0x00, 0x00];
        b.extend_from_slice(&[0xff, 0xc0, 0x00, 0x11, 0x08]);
        b.extend_from_slice(&600u16.to_be_bytes()); // height first
        b.extend_from_slice(&800u16.to_be_bytes());
        b.extend_from_slice(&[0; 8]);
        assert_eq!(probe("x.jpg", &b), Some(Media::Image { w: 800, h: 600 }));
    }

    #[test]
    fn an_svg_falls_back_to_its_viewbox() {
        let with_size = br#"<svg width="64" height="32" xmlns="http://www.w3.org/2000/svg">"#;
        assert_eq!(probe("i.svg", with_size), Some(Media::Image { w: 64, h: 32 }));
        let only_box = br#"<svg viewBox="0 0 24 16" xmlns="http://www.w3.org/2000/svg">"#;
        assert_eq!(probe("i.svg", only_box), Some(Media::Image { w: 24, h: 16 }));
        // Units we cannot resolve are not guessed at.
        let in_mm = br#"<svg width="210mm" height="297mm">"#;
        assert_eq!(probe("i.svg", in_mm), Some(Media::Image { w: 210, h: 297 }));
    }

    #[test]
    fn what_is_not_a_picture_is_left_alone() {
        assert_eq!(probe("main.rs", b"fn main() {}"), None);
        assert_eq!(probe("x.png", b"not a png"), None);
        assert!(is_media("docs/a.PNG"));
        assert!(is_media("paper.pdf"));
        assert!(!is_media("main.rs"));
        assert!(!is_media(".gitignore"));
    }

    #[test]
    fn a_pdf_reports_its_pages_and_page_size() {
        let doc = b"%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n\
                    2 0 obj\n<< /Type /Pages /Count 42 /Kids [3 0 R] >>\nendobj\n\
                    3 0 obj\n<< /Type /Page /MediaBox [0 0 595 842] >>\nendobj\n";
        assert_eq!(probe("p.pdf", doc), Some(Media::Document { pages: 42, w: 595, h: 842 }));
    }

    #[test]
    fn an_outlines_count_is_not_a_page_count() {
        // What cost five of the twenty five documents I measured against.
        let doc = b"%PDF-1.4\n1 0 obj\n<< /Type /Outlines /Count 11 >>\nendobj\n\
                    2 0 obj\n<< /Type /Pages /Count 7 /Kids [3 0 R] >>\nendobj\n\
                    3 0 obj\n<< /Type /Page /MediaBox [0 0 612 792] >>\nendobj\n";
        assert_eq!(probe("p.pdf", doc), Some(Media::Document { pages: 7, w: 612, h: 792 }));
    }

    #[test]
    fn a_pdf_that_hides_its_page_tree_says_it_does_not_know() {
        // Everything in an object stream, which is a third of the PDFs I have.
        let doc = b"%PDF-1.5\n4 0 obj\n<< /Type /ObjStm /N 12 /Length 900 >>\nstream\n\
                    (compressed)\nendstream\nendobj\n";
        assert_eq!(probe("p.pdf", doc), Some(Media::Document { pages: 0, w: 0, h: 0 }));
        // And is still sized as one A4 page rather than as nothing.
        let m = Media::Document { pages: 0, w: 0, h: 0 };
        assert_eq!(m.pixels(), 595 * 842);
        assert!((m.aspect() - 595.0 / 842.0).abs() < 1e-6);
    }

    #[test]
    fn size_and_shape_come_out_of_the_header() {
        let wide = Media::Image { w: 1600, h: 900 };
        assert!((wide.aspect() - 16.0 / 9.0).abs() < 1e-6);
        assert_eq!(wide.pixels(), 1_440_000);
        // A page is portrait, and three pages are three times the area.
        let doc = Media::Document { pages: 3, w: 595, h: 842 };
        assert!(doc.aspect() < 1.0);
        assert_eq!(doc.pixels(), 3 * 595 * 842);
        // Nothing useful in the header is a square of unknown size.
        assert_eq!(Media::Image { w: 0, h: 0 }.aspect(), 1.0);
    }
}
