<script lang="ts">
	// Generated by web/scripts/make-icon.mjs. Edit that, not this: the same
	// drawing is the app icon and the favicon, and the three drifting apart is
	// exactly what one source of geometry is for.
	//
	// The panels take the theme's colours so the mark sits on a light palette as
	// well as a dark one. The red does not: it is the signature, and it stays
	// the one thing on screen at full saturation.
	let { height = 16 }: { height?: number } = $props();
</script>

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width={height} height={height} role="img" aria-label="sanity">
    <rect x="0" y="0" width="1024" height="1024" rx="112" fill="var(--bg)"/>
  <rect x="117.8" y="117.8" width="459" height="469" rx="12.6" fill="var(--text)"/>
  <rect x="117.8" y="616.7" width="459" height="289.5" rx="12.6" fill="var(--sanity-red)"/>
  <rect x="606.7" y="117.8" width="299.5" height="379.3" rx="12.6" fill="var(--text)"/>
  <rect x="606.7" y="527" width="299.5" height="379.3" rx="12.6" fill="var(--text-dim)"/>
</svg>

<style>
	svg {
		display: block;
		flex: none;
	}
</style>
